version: '3.9'
################## NETWORKS ####
networks:
  proxy:
    external: true

################## SERVICES ####
services:
  ###################
  #### PORTAINER ####
  ###################
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    hostname: portainer
    ports:
      - 8000:8000
      - 9061:9000
      # - 9443:9443
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKER_DIR/appdata/docker-management/portainer:/data
    environment:
      - VIRTUAL_HOST=portainer.$DOMAINNAME
      - VIRTUAL_PORT=9061
    labels:
      ## Enable Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      ## HTTP Routers
      - "traefik.http.routers.portainer-rtr.rule=Host(`portainer.home.$DOMAINNAME`,`portainer.$DOMAINNAME`)"
      - "traefik.http.routers.portainer-rtr.entrypoints=https"
      - "traefik.http.routers.portainer-rtr.tls=true"
      ## HTTP Services
      # - "traefik.http.routers.portainer-rtr.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
      ## Middlewares
      # - "traefik.http.routers.portainer-rtr.middlewares=authelia@docker" #middlewares-authentik@file"
      ## edge-agent
      # - "traefik.http.routers.portainer-edge.entrypoints=https"
      # - "traefik.http.routers.portainer-edge.rule=Host(`portainer-edge.$DOMAINNAME`)"
      # - "traefik.http.routers.portainer-edge.tls=true"
      # - "traefik.http.services.portainer-edge.loadbalancer.server.port=9443"
      # - "traefik.tcp.routers.portainer-edge-tcp.entrypoints=tcp"
      # - "traefik.tcp.routers.portainer-edge-tcp.rule=HostSNI(`*`)"
      # - "traefik.tcp.services.portainer-edge-tcp.loadbalancer.server.port=8000"
      # # - "traefik.http.routers.portainer-edge-tcp.middlewares=authelia@docker"  #middlewares-authentik@file"
    command: -H unix:///var/run/docker.sock
    restart: always

  ################
  #### DOCKGE ####
  ################
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 9150:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKER_DIR/appdata/docker-management/dockge:/app/data
      - $DOCKER_DIR/appdata:$DOCKER_DIR/appdata 
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Your stacks directory in the host (The paths inside container must be the same as the host)
      # ⚠️⚠️ If you did it wrong, your data could end up be written into a wrong path.
      # ✔️✔️✔️✔️ CORRECT: - /my-stacks:/my-stacks (Both paths match)
      # ❌❌❌❌ WRONG: - /docker:/my-stacks (Both paths do not match)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=$DOCKER_DIR/appdata
    labels:
      ## Enable Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      ## HTTP Routers
      - "traefik.http.routers.dockge-rtr.entrypoints=https"
      - "traefik.http.routers.dockge-rtr.priority=100"
      - "traefik.http.routers.dockge-rtr.rule=Host(`dockge.home.niang.be`)" #",`dockge.niang.be`)"
      - "traefik.http.routers.dockge-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.dockge-rtr.middlewares=authelia@docker" #middlewares-authentik@file"
      ## HTTP Services
      - "traefik.http.services.dockge-svc.loadbalancer.server.port=80"
